version: '3'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - './project:/var/www/html'
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './project:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306

